domainKeyword:
  - "2pcdn."
  - "bsccdn"
  - "-hcdn."
  - "p2p-"
  - "p2p."
  - "p2pchunk-"
  - "p2perrorlog."
  - "p2plive"
  - "p2plive-"
  - "p2plog"
  - "p2plog."
  - "p2ptun."
  - "p2pupdate."
  - "p2pupgrade."
  - "p2pvod-"
  - "-pcdn"
  - "pcdn.xmcdn."
  - "xycdn."
  - "yfcdn."
  - "yfp2p."
  - "anonfiles"
  - "httpsdns"
  - "https-dns"
  - "https.dns"
  - "httpdns"
  - "http-dns"
  - "http.dns"
  - "cdndns"
  - "cdn-dns"
  - "cdn.dns"
  - "dnscdn"
  - "dns-cdn"
  - "dns.cdn"
  - "apidns"
  - "api-dns"
  - "api.dns"
  - "dnsapi"
  - "dns-api"
  - "dns.api"
  - "dns.weixin"
  - "better365"
  - ".log."
  - "app-analytics"
  - "analytics."
  - "monitor"
  - "pclog."
  - "applog."
  - "ioslog."
  - "pc-log."
  - "app-log."
  - "ios-log."
  - ".ad."
  - ".ad-"
  - "-ad."
  - ".ads."
  - ".ads-"
  - "guide-acs.taobao.com"
  - "amdc.m.taobao.com"
  - "gjfzpt"
  - "chanct"
  - "fzlm"
  - "fqzpt"